name: sat_atender_representante
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
#Basics
  flutter_modular: ^5.0.3
  mobx: ^2.0.7+5
  flutter_mobx: ^2.0.6+1
  flutter_svg: ^1.1.5

#Others
  pluto_grid: ^5.4.4
  # google_fonts: ^3.0.1
  # syncfusion_flutter_datagrid: ^20.2.50
  # syncfusion_flutter_core: ^20.3.49  
  # path_provider: ^2.0.11
  # file_picker: ^5.2.4
  
  comum: 
    path: ../comum
  
  intl: ^0.17.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.7
  build_runner: ^2.2.0

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/img/
    - assets/svg/

scripts:
  mobx: flutter pub run build_runner watch --delete-conflicting-outputs